
<h3>Terms of Use</h3>

<p><strong>General Statement</strong><br/>
Before using our website, you should read these Terms of Use, our other policies, and the instructions published on this site. Access, use, or continued use of our website BEEx.org means that you agree to our Terms of Use and policies, and your permission to use our site is contingent upon your agreement. If you do not agree to our Terms of Use and other policies, then we must expressly revoke your permission to use our site, and ask that you please do not use BEEx.org.</p>
<p>We make best efforts to maintain our information and site, but are not responsible for the results of any error or defect in BEEx.org that may result in a claim for lost profits or other incidental or consequential damage. Our website, tools, information, and/or services are provided to you "as-is" and without warranty. Accordingly, you should not assume that BEEx.org or any particular content, including content uploaded by you, us, or by other users, is error-free or that it will be suitable for a particular purpose that you have in mind.</p>
<p>We may, for a number of reasons and at our discretion, modify, discontinue, limit, terminate, or suspend your use of, or access to, BEEx.org. Some of these reasons are listed below, but this should not be read as a complete list of reasons why someone will need to be removed, blocked, or prevented from using our site.</p>
<p>We may need to make changes to our Terms of Use and other policies. We will keep a current version of the Terms of Use, other information and policies on our site.</p>
<p><strong>Profiles and Account Usage<br/>
</strong> To use BEEx.org, you will need a profile or an account with us. To generate a profile you must read and accept all of the terms, conditions, and policies that we publish on our site. We will need certain information from you to generate your profile. Please read our privacy policy regarding information that you share with us, and information that you choose to share with others.</p>
<p>You will choose your own password to access your profile, and you are responsible for maintaining the confidentiality of your password. Generally, you should not share access to your profile with others, and we cannot be responsible if you share access to your profile or allow others access to your personal information. Instead, keep your password in a secure place and do not give out your password, or allow any unauthorized persons access to your profile, account, and information. If you become aware of any unauthorized or suspicious use of your password, profile, or other potential breach or misuse, please notify us immediately.</p>
<p>You understand and agree that we may review usage of BEEx.org including content that appears on our site. Users who, or content that, violates our terms or other policies, or which might be offensive, illegal, harmful, affect safety, or violate the rights of others may be removed. Content that is illegal or prohibited, includes, but is not limited to, material, text, graphics, video or audio that:</p>
<p>&bull;    Is unlawful, harassing, libelous, abusive, threatening, harmful, bigoted, racially offensive, obscene, or otherwise objectionable;</p>
<p>&bull;    Displays sexually explicit/graphic material of any kind;</p>
<p>&bull;    Encourages conduct that could constitute a criminal offense, gives rise to civil liability or otherwise violate any applicable local, state, national or international law or regulation; and/or</p>
<p>&bull;    Collects, stores, advertises, markets or solicits information to or about users or others for commercial or unlawful purposes or engage in commercial activity such as contests, sweepstakes, etc. without our prior consent.</p>
<p>As an authorized user of this website, you may terminate your access and usage of the site at your discretion at any time by sending an email to [folks@beex.org], and we will terminate your account. Existing content, challenges, and other information that you have uploaded or provided may remain on our site so as not to disrupt activities of, or services to, other users. As mentioned above, we may need, at our discretion and at any time, to terminate or suspend our service or website, your profile, and/or your access without notice to you for a number of reasons including, but not limited to, violation of our terms or policies, safety concerns, to comply with legal requirements or authorities, or for another reason. BeExtraordinary does not condone the performance of dangerous, malicious, or criminal activities or "stunts" including, but not limited to, those activities that are expressly prohibited by federal, state, local, and/or municipal law. We are not responsible in any way for injury occurring while performing a challenge, and BeExtraordinary will cancel or remove your challenge from our site if we reasonably view it as being dangerous or harmful to the participants or others, including animals and property.</p>
<p><strong>Refunds and Cancellations<br/>
</strong> Refunds and cancellations will be given to users who made a mistake while donating to a challenge. Unfortunately, we cannot refund your money if a challenger fails to complete a challenge or does not post sufficient proof in a timely manner. To request a refund, contact us within 15 days of the transaction you wish cancel/have refunded. After that time period, all transactions are final. Please also note that once a challenge's completion date arrives, all challenge-related transactions are final.<br/>
To Request a Refund</p>
<p>&bull;    Contact a representative of BeExtraordinary at folks@beex.org<br/>
&bull;    Call our customer support line at 212.965.0009</p>
<p><strong>Security<br/>
</strong>BEEx.org is a secure site. We use SSL (https:// functionality) so all of your data is encrypted and secure.</p>
